In [9]:
import pandas as pd  

# Charger le fichier TXT (ajuster le séparateur si nécessaire)
df = pd.read_csv(r"C:\Users\koudouya\Downloads\caracteristiques-2021.txt", sep="\t", encoding="utf-8")   

# Exporter en fichier Excel
df.to_excel("mon_fichier.xlsx", index=False)  

print("Fichier Excel créé avec succès !")

Fichier Excel créé avec succès !

In [10]:
df

,Num_Acc,jour,mois,an,hrmn,lum,com,agg,int,atm,col,adr,lat,long
0,202100037733,28,5,2021,14:15,1,CC_97407,2,2,1,3,JEAN MOULIN (RUE) - RIV. DES GALETS,"-20,95888","55,31743"
1,202100049382,2,3,2021,10:59,1,CC_63113,2,1,1,2,SAINT ROBERT (RUE),"45,79137","3,1162"
2,202100038891,20,5,2021,16:50,1,CC_88160,2,2,1,1,POISSOMPRE (FG DE),"48,18261","6,47218"
3,202100028616,14,7,2021,19:45,1,CC_80021,2,1,1,3,CAGNARD (RUE),"49,90355","2,2872"
4,202100033509,17,6,2021,23:40,3,CC_13214,2,1,1,1,A7-Sens Lyon vers Marseille,"43,34031","5,37689"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56525,202100026753,28,7,2021,17:10,1,CC_38474,2,2,1,3,Rue du Vinay,"45,204957","5,667561"
56526,202100019814,10,9,2021,06:15,3,CC_77251,1,1,1,7,RN 104,"48,631","2,533"
56527,202100016048,29,9,2021,08:15,1,CC_78524,1,1,1,3,A13,"48,841059","2,106997"
56528,202100039830,15,5,2021,06:45,2,CC_13212,2,2,1,3,PIERRE CHEVALIER (avenue),"43,2953","5,4254"
56529,202100046742,13,3,2021,09:30,1,CC_76108,2,1,2,7,HAIE. RUE DE LA,"49,46523106","1,112713775"

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56530 entries, 0 to 56529
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Num_Acc  56530 non-null  int64
 1   jour     56530 non-null  int64
 2   mois     56530 non-null  int64
 3   an       56530 non-null  int64
 4   hrmn     56530 non-null  object
 5   lum      56530 non-null  int64
 6   com      56530 non-null  object
 7   agg      56530 non-null  int64
 8   int      56530 non-null  int64
 9   atm      56530 non-null  int64
 10  col      56530 non-null  int64
 11  adr      55957 non-null  object
 12  lat      56530 non-null  object
 13  long     56530 non-null  object
dtypes: int64(9), object(5)
memory usage: 6.0+ MB